
{{ config(
    materialized='view',
    schema='IM',
    override_schema=True 
) }}

SELECT
    CUSTOMER_ID,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(ORDER_TOTAL_AMOUNT) AS TOTAL_SPENT,
    AVG(ORDER_TOTAL_AMOUNT) AS AVERAGE_ORDER_VALUE,
    MAX(ORDER_TOTAL_AMOUNT) AS HIGHEST_ORDER_VALUE,
    MIN(ORDER_TOTAL_AMOUNT) AS LOWEST_ORDER_VALUE,
    SUM(TOTAL_ITEMS_COUNT) AS TOTAL_ITEMS_PURCHASED,
    AVG(TOTAL_ITEMS_COUNT) AS AVERAGE_ITEMS_PER_ORDER,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF(DAY, MIN(ORDER_DATE), MAX(ORDER_DATE)) AS CUSTOMER_LIFETIME_DAYS
    -- SUM(CASE WHEN IS_COMPLETED THEN 1 ELSE 0 END) AS COMPLETED_ORDERS,
    -- SUM(CASE WHEN IS_CANCELLED THEN 1 ELSE 0 END) AS CANCELLED_ORDERS,
    -- CASE
    --     WHEN SUM(ORDER_TOTAL_AMOUNT) >= 5000 THEN 'VIP'
    --     WHEN SUM(ORDER_TOTAL_AMOUNT) >= 2000 THEN 'PREMIUM'
    --     WHEN SUM(ORDER_TOTAL_AMOUNT) >= 1000 THEN 'REGULAR'
    --     ELSE 'BASIC'
    -- END AS CUSTOMER_TIER
FROM {{ ref('fact_order_summary') }}
GROUP BY CUSTOMER_ID