name: run dbt CI Cloud job on NONPROD
 
# This works off the assumption that you've restricted this branch to only all PRs to push to the main branch
on:
  pull_request:
    branches: [main]
 
jobs:
 
  # the job calls the dbt Cloud API to run a job
  run_dbt_cloud_job:
    name: run dbt CI Cloud job on NONPROD
    runs-on: CAI-Enterprise
 
  # Set the environment variables needed for the run
    env:
      DBT_URL: "https://cloud.getdbt.com"
      DBT_ACCOUNT_ID:  ${{ vars.DBT_ACCOUNT_ID }}
      DBT_PROJECT_ID:  ${{ vars.DBT_PROJECT_ID }}
      DBT_PR_JOB_ID:   ${{ vars.DBT_NONPROD_CI_JOB_ID }}
      DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
      DBT_JOB_CAUSE: 'GitHub Pipeline CI Job'
      DBT_JOB_BRANCH: ${{ github.head_ref }}
      DBT_JOB_SCHEMA_OVERRIDE: 'DBT_CI_JOB_${{ github.event.number }}_${{github.run_number}}'
 
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"
      - name: Run dbt Cloud job
        run: "python scripts/run_and_monitor_dbt_job.py"