name: run dbt Deploy Cloud job
 
# This filter says only run this job when there is a push to the main branch
# This works off the assumption that you've restricted this branch to only all PRs to push to the default branch
# Update the name to match the name of your default branch
on:
  workflow_dispatch:
    inputs:
      dbt_environment:
        type: environment
        default: nonprod
        description: Deploy to dbt
      crq_description:
        type: string
        description: Change request description
 
jobs:
  run_dbt_cloud_CI_job:
    if: ${{ inputs.dbt_environment == 'prod' }}
    name: Run dbt CI Cloud Job
    runs-on: ubuntu-latest
 
  # Set the environment variables needed for the run
    env:
      DBT_URL: "https://if991.us1.dbt.com"
      DBT_ACCOUNT_ID:  ${{ vars.DBT_ACCOUNT_ID }}
      DBT_PROJECT_ID:  ${{ vars.DBT_PROJECT_ID }}
      DBT_PR_JOB_ID:   ${{ vars.DBT_PROD_CI_JOB_ID }}
      DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
      DBT_JOB_CAUSE: 'GitHub Pipeline CI Job'
      DBT_JOB_BRANCH: ${{ github.ref_name }}
      DBT_JOB_SCHEMA_OVERRIDE: 'DBT_CI_JOB_${{github.run_number}}'
 
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"
      - name: Run dbt Cloud job
        run: "python scripts/run_and_monitor_dbt_job.py"
  run_dbt_cloud_CD_job:
    needs: run_dbt_cloud_CI_job
    if: ${{ always() && (needs.run_dbt_cloud_CI_job.result == 'skipped' || needs.run_dbt_cloud_CI_job.result == 'success') }}
    name: Run dbt Deploy Cloud Job
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.dbt_environment }}
 
  # Set the environment variables needed for the run
    env:
      DBT_URL: "https://if991.us1.dbt.com"
      DBT_ACCOUNT_ID:  ${{ vars.DBT_ACCOUNT_ID }}
      DBT_PROJECT_ID:  ${{ vars.DBT_PROJECT_ID }}
      DBT_PR_JOB_ID:   ${{ vars.DBT_CD_JOB_ID }}
      DBT_API_KEY: ${{ secrets.DBT_API_KEY }}
      DBT_JOB_CAUSE: 'GitHub Pipeline Deploy Job'
      DBT_JOB_BRANCH: ${{ github.ref_name }}
 
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"
      - name: Run dbt Cloud job
        run: "python scripts/run_and_monitor_dbt_job.py"